### ISSUE TITLE
TypeError: Cannot read property 'access_token' of null

### ISSUE THREAD

**Issue by sadortun** [cedpoilly/vue-gapi#50] opened 2020-05-16 22:08 UTC
Hi !

First of all, thanks for your great library! 

Unfortunatly, when using  `this.$gapi.login()`  i receive the following error : 
```
cb=gapi.loaded_0:181 Uncaught TypeError: Cannot read property 'access_token' of null
    at GoogleAuthService._setStorage (vue-gapi.common.js?15fd:83)
    at GoogleAuthService._setSession (vue-gapi.common.js?15fd:134)
    at eval (vue-gapi.common.js?15fd:155)
    at e.Sr (cb=gapi.loaded_0:192)
    at Lk (cb=gapi.loaded_0:195)
    at Gk (cb=gapi.loaded_0:195)
    at _.rk.xU (cb=gapi.loaded_0:195)
    at ok (cb=gapi.loaded_0:186)
```

Looking at the parent method,  the `response` is almost empty.

![image](https://user-images.githubusercontent.com/794449/82131098-b629ac00-979f-11ea-963b-383d6445b04c.png)

The profile info is there : 
![image](https://user-images.githubusercontent.com/794449/82131452-50d7ba00-97a3-11ea-882c-eb86b16b1bd1.png)

If i call `$gapi.login()` a second time, everything works fine.
Also, if i refresh the page, i am logged in correctly

Thanks for your help,
Samuel

**Comment by cedpoilly** [comment] 2020-05-17 06:15
Hi @sadortun ,

Thanks for using VueGAPI!

Can you please provide more context on this?

Also, I have to ask: are you calling `this.gapi.login()` as an `async` method?
Meaning: are you calling `.then` on it or using `async..await`?

Cheers,
Cedric

**Comment by sadortun** [comment] 2020-05-17 19:17
Hi @cedpoilly 

Here is our login method
```
      userSignInWithGoogle ()
      {
        var promises = []
        promises.push(new Promise((resolve, reject) => {
          this.$gapi.getGapiClient()
            .then(gapi => {
              this.$gapi.login().then(function () {
                const token = gapi.auth.getToken()
                if (token)
                {
// .....
              })
            }
        }))
// ...
        Promise.all(promises).then(function () {
// ...
        })
      },
```

**Comment by vinicius1209** [comment] 2020-05-26 01:55
I'm having the same issue in my app. Calling this.$gapi.login() automatically "close" the promises. Whatever is inside then() the function not wait the completed login.

**Comment by vinicius1209** [comment] 2020-05-26 02:00
@sadortun any updates? did you get a momentary solution?

**Comment by sadortun** [comment] 2020-05-26 03:11
@vinicius1209  Yes and no, i am using GAPI without `vue-gapi`

**Comment by vinicius1209** [comment] 2020-05-26 03:26
> @vinicius1209 Yes and no, i am using GAPI without `vue-gapi`

Oh yes... I am try to use only GAPI using vue but I don’t know how to figure out. If u can provide an example I will appreciate it a lot!

**Comment by sadortun** [comment] 2020-05-26 03:59
Something like that

```
        const auth = window.gapi.auth2.getAuthInstance()
        auth.then(() => {
          auth.signIn(/*{
            'prompt':     'select_account',
            'grant_type': 'authorization_code',
          }*/).then(offlineAccessExchangeCode => {
            // send offline access exchange code to server ...
})
})
```

**Comment by cedpoilly** [comment] 2020-05-26 11:17
@sadortun @vinicius1209 This works on my app:

```js
// once authenticated:
const accessToken = await this.gapi.auth.getToken().access_token;
```

**Comment by namoscato** [comment] 2020-05-30 13:10
@cedpoilly, this was introduced with the change from `GoogleAuth.signIn()` to `GoogleAuth.grantOfflineAccess()` in https://github.com/cedpoilly/vue-gapi/compare/v0.1.2...v0.2.2:

https://github.com/cedpoilly/vue-gapi/blob/8f1c403bce4bb5955a085257bb89a4d63b1b2803/src/VueGAPI/GoogleAuthService.js#L120-L126

In the current state, the subsequent `_setSession` call to `GoogleUser.getAuthResponse()` is returning `null`.

I'm not sure why that is happening off the top of my head, but why was the change made from `signIn` to `grantOfflineAccess`? This seems like a less than ideal default.

**Comment by cedpoilly** [comment] 2020-06-01 08:05
@namoscato Thanks for the info & feedback! I missed that regression. `grantOfflineAccess` is used so that we can get access to the `refresh_token`. Let me work on that.

Would you like to help with this feature and improving the repo as a whole?

**Comment by namoscato** [comment] 2020-06-01 11:28
@cedpoilly, no problem! I would be happy to help out when I can, but I cannot commit a ton of time at the moment.

**Comment by everttrollip** [comment] 2020-06-01 17:09
I noticed the same as @namoscato in that the error seems to only happen after the change from `GoogleAuth.signIn()` to `GoogleAuth.grantOfflineAccess()`. Did you manage to find anything yet @cedpoilly ?

**Comment by everttrollip** [comment] 2020-06-04 06:08
@cedpoilly any chance you maybe had some time to look into the problems caused by `grantOfflineAccess`?

**Comment by cedpoilly** [comment] 2020-06-04 06:14
@everttrollip checking it today. Would you like to pair up?

**Comment by cedpoilly** [comment] 2020-06-04 07:59
@everttrollip @sadortun @namoscato @vinicius1209 I have a working prototype. Still needs some fine tuning & testing. Stay tuned 🤙

**Comment by everttrollip** [comment] 2020-06-04 09:11
@cedpoilly I don't mind trying to help you out! How would you like to pair up?

**Comment by everttrollip** [comment] 2020-06-04 09:13
@cedpoilly that's awesome that you got a working prototype. If I can still help out, please let me know. I'm also working, so that's why it took me so long to respond...

**Comment by cedpoilly** [comment] 2020-06-04 09:21
@everttrollip email me so we can set it up ✌️

**Comment by cedpoilly** [comment] 2020-06-06 17:31
@everttrollip @sadortun @namoscato @vinicius1209 I have just published the fix: **0.3.1**

Kindly check and let me know ✌

**Comment by everttrollip** [comment] 2020-06-20 09:41
@cedpoilly I can confirm this seems to work without problems. Thank you for the fix!

**Comment by namoscato** [comment] 2020-07-02 11:03
This also looks good in my context as well – thanks @cedpoilly! I'm going to close this out.

**Closed by namoscato** 2020-07-02 11:03 UTC
Labels: bug
